settings:
  access_secret: oY6CJphyCXsfQnj1h680ovhdPFoSWK9msAp34IHU4sRNx
  access_token: 36620718-PAlXuTv5nVo1mRyPf7CqHzCgtMT84pkFksdososs0
  consumer_key: A8BdqFZb6pX6nzdC55b7xJbaJ
  consumer_secret: fyRbYzEDlfP6lLilmN6Sl5laaTW0NWRdKevWnI1dGwvCbbJBIL
  id: 333
  name: Twitter Miner Three
  parenturi: http://localhost:4000
  users: watty62, SymboticaAndrew, lilmisstee, digitalWestie, davemor
