access_secret: ***REMOVED***
access_token: ***REMOVED***
batch_size: '6'
consumer_key: ***REMOVED***
consumer_secret: ***REMOVED***
name: Tirami Robot Miner
parent_uri: http://localhost:4000
queue_time: '10'
users: tirami_dave
