access_secret: ***REMOVED***
access_token: ***REMOVED***
consumer_key: ***REMOVED***
consumer_secret: ***REMOVED***
id: '001'
name: Twitter Miner One
parent_uri: http://localhost:4000
users: tirami_dave, watty62, SymboticaAndrew, lilmisstee, digitalWestie, davemor
