access_secret: elupRjXgEx6uCdtjyZFwHl1JeVCZHu8dYBnyCGhfCbG6i
access_token: 4829129267-9NKXGxpBOSz5NKggOI74pa4WH6fe8JzQAuh0sI9
batch_size: '10'
consumer_key: LUwW7tWhpozdo9VveJ2iroru6
consumer_secret: kqu06bDk7YnMljefphMVMOnwG3XyD4e5RejT62vLSM92gggKmA
name: Nairobi Live Engine Twitter
parent_uri: http://udadisi-engine-env-1.eu-west-1.elasticbeanstalk.com
queue_time: '10'
users: mwebafrica, BAKE_ke, iHub, AfricaResearch, UPNairobi, akirachix, NairobiGarage,
  gearboxKE, bonifacemwangi, afrigadget, brcknet, iHubResearch, VirtualKenya, sanergy,
  county_nairobi, ermarchant, KenyaOpenData, kiwanja, TetraTechIntDev, ICTAuthorityKE
