access_secret: ***REMOVED***
access_token: ***REMOVED***
batch_size: '10'
consumer_key: ***REMOVED***
consumer_secret: ***REMOVED***
name: Dhaka Live Engine Twitter
parent_uri: http://localhost:4000
queue_time: '10'
users: global_rec, Ehsan_Dhaka, DAM_UK, BRACworld, Amcariza, UNDP_BD, snehalsoneji,
  OxfaminBD, AABangladesh, aditya_whara, SciDevNet, DhakaTribune, PracticalAction,
  hmirfanullah, s_ayebkarlsson, onindita_islam, CIPRB
