access_secret: elupRjXgEx6uCdtjyZFwHl1JeVCZHu8dYBnyCGhfCbG6i
access_token: 4829129267-9NKXGxpBOSz5NKggOI74pa4WH6fe8JzQAuh0sI9
consumer_key: LUwW7tWhpozdo9VveJ2iroru6
consumer_secret: kqu06bDk7YnMljefphMVMOnwG3XyD4e5RejT62vLSM92gggKmA
id: !!python/unicode '002'
name: Twitter Miner Two
parent_uri: http://localhost:4000
users: tirami_dave
