access_secret: elupRjXgEx6uCdtjyZFwHl1JeVCZHu8dYBnyCGhfCbG6i
access_token: 4829129267-9NKXGxpBOSz5NKggOI74pa4WH6fe8JzQAuh0sI9
batch_size: '100'
consumer_key: LUwW7tWhpozdo9VveJ2iroru6
consumer_secret: kqu06bDk7YnMljefphMVMOnwG3XyD4e5RejT62vLSM92gggKmA
name: Lima Live Engine Twitter
parent_uri: http://engine.udadisi.com
queue_time: '10'
users: SolucionesP, SaveChildrenPe, WorldRuralForum, cgiarclimate_LA, omarcelob, MINPRODUCCION, CooperAccionPER, Agro_Noticia, biodesarrollo, IICAnoticias, WorldVisionPeru, ecosostenible, observatierras, GobernanzaPE, cidrusa, SciDevNet_AL