access_secret: elupRjXgEx6uCdtjyZFwHl1JeVCZHu8dYBnyCGhfCbG6i
access_token: 4829129267-9NKXGxpBOSz5NKggOI74pa4WH6fe8JzQAuh0sI9
batch_size: '100'
consumer_key: LUwW7tWhpozdo9VveJ2iroru6
consumer_secret: kqu06bDk7YnMljefphMVMOnwG3XyD4e5RejT62vLSM92gggKmA
name: Dhaka Live Engine Twitter
parent_uri: http://engine.udadisi.com
queue_time: '100'
users: global_rec, Ehsan_Dhaka, DAM_UK, BRACworld, Amcariza, UNDP_BD, snehalsoneji,
  OxfaminBD, AABangladesh, aditya_whara, SciDevNet, DhakaTribune, PracticalAction,
  hmirfanullah, s_ayebkarlsson, onindita_islam, CIPRB
