access_secret: ***REMOVED***
access_token: ***REMOVED***
batch_size: '100'
consumer_key: ***REMOVED***
consumer_secret: ***REMOVED***
name: Lima Live Engine Twitter
parent_uri: http://localhost:4000
queue_time: '10'
users: SolucionesP, SaveChildrenPe, WorldRuralForum, cgiarclimate_LA, omarcelob, MINPRODUCCION,
  CooperAccionPER, Agro_Noticia, biodesarrollo, IICAnoticias, WorldVisionPeru, ecosostenible,
  observatierras, GobernanzaPE, cidrusa, SciDevNet_AL
